### ISSUE TITLE
pos = @data.rindex(METADATA_BEGIN_MARKER) is not able to find "\xAB\xCD\xEFMaxMind.com" in my newly purchased mmdb.

### ISSUE THREAD

**Issue by emresurmeli** [yhirose/maxminddb#30] opened 2017-07-26 20:21 UTC
I have File.binread(<my_mmdb_location>) and ran file.rindex(METADATA_BEGIN_MARKER) manually in rails console. And am unable to find the starting point of the metadata in the DB.

I see the last update to this repo was about a month ago. Any one else having this issue?

**Comment by yhirose** [comment] 2017-07-26 21:24
@emresurmeli, thank you for the report. Recent change is just a minor change. So I don't think it affects. Also I confirmed that all unit tests pass with the latest free-downloadable GeoLite2-City.mmdb and GeoLite2-Country.mmdb (as of 7-26-2017).

I am trying to reproduce your problem with the latest Geo-Lite2-City.mmdb. Here is my test code and result:
```bash
$ cat test.rb 
METADATA_BEGIN_MARKER = ([0xAB, 0xCD, 0xEF].pack('C*') + 'MaxMind.com').encode('ascii-8bit', 'ascii-8bit')
data = File.binread('./GeoLite2-City.mmdb')
pos = data.rindex(METADATA_BEGIN_MARKER)
raise 'invalid data format' unless pos
p pos

$ ruby test.rb 
53829481
```

What result do you get with your purchased database? (position, or 'invalid data format' error message?)

Thanks for your assistance!

**Comment by emresurmeli** [comment] 2017-07-27 16:15
Correct, I get 'file format'. Here is my initializer for it. 

path = File.join Rails.root, 'config', 'initializers', 'GeoIP2-City.mmdb'
Rails.application.config.max_mind = MaxMindDB.new( path )

I tested the code you gave me, and it does seem to work. But for some reason, it doesn't in my rails app.

**Comment by yhirose** [comment] 2017-07-27 22:21
Thanks for the update. It's really interesting. I would be happy to look into it.
Since I don't have any experience with rails, I don't fully understand what's going on. Is there any easy way to reproduce the problem on my machine with the free-downloadable 'GeoLite2-City.mmdb'?

**Comment by yhirose** [comment] 2017-09-06 19:25
I'll close it for now, because no one else reports it. But please let me know if you find more information regarding this. Thanks!

**Closed by yhirose** 2017-09-06 19:25 UTC
